Build:
    # parameters for the build
    Distro:
        - Ubuntu

    Platform:
        - D02
        - D03
DISTRO:
    D02:
        - Ubuntu: Ubuntu_ARM64.tar.gz
        - Fedora: Fedora_ARM64.tar.gz
        - OpenSuse: OpenSuse_ARM64.tar.gz
        - Debian: Debian_ARM64.tar.gz
        - CentOS: CentOS_ARM64.tar.gz
        - Rancher: Rancher_ARM64.tar.gz
    D03:
        - Ubuntu: Ubuntu_ARM64.tar.gz
        - Fedora: Fedora_ARM64.tar.gz
        - OpenSuse: OpenSuse_ARM64.tar.gz
        - Debian: Debian_ARM64.tar.gz
        - CentOS: CentOS_ARM64.tar.gz
        - Rancher: Rancher_ARM64.tar.gz
    D05:
        - CentOS: CentOS_ARM64.tar.gz
        - Ubuntu: Ubuntu_ARM64.tar.gz

# the dictionary for the board and arch mapping
Arch:
    d05: arm64
    d03: arm64
    d02: arm64

# for lava connection
#    TOKEN: p53l26plbujbqaicsrkw0i1u3xu5qawxlx3imr41w3eiwg1y79jxtjkx209p2kccsc1obzy279c7ruydhskzotdlf6s3me0wb87o0rf71m0sehetlje9p0cr0dorkhf8
LAVA:
    USER: htsat
    HOST: 192.168.3.100
    TOKEN: g43y0wtyi0m2ua7in3xtfch1m2s1dd0k97ac1fqqhqd0qblimtehqkwk8mjimsyh0jczrnaibdlb23mtn17qca6i14tcl27h7md580za5p8w81fl035b6bk1ybw26lle
    lavaserver: http://192.168.3.100/RPC2/
    lavastream: /anonymous/default/
    lavauser: default

# for lava job parameter
Jenkins:
    Boot: boot
    App:
        - WEEKLY_TESTING
        - TEST

# for kernelci access
Kernelci:
    server: http://192.168.108:8083
    token: 3eda8013-da37-42ea-b9a0-7a66badd1b68
    ftpserver: http://192.168.1.108:8083
